/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/health-bot.glb --types --debug 
Author: Matt Harris (https://sketchfab.com/MattHarris86)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/health-bot-animations-406306938e0d44aeac8d4b4ca7121d99
Title: Health-Bot Animations
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'HealthbotAnimations'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_27: THREE.SkinnedMesh
    Object_29: THREE.SkinnedMesh
    Object_31: THREE.SkinnedMesh
    Object_33: THREE.SkinnedMesh
    Object_47: THREE.SkinnedMesh
    Wing_RightFlap_blinn2_0: THREE.Mesh
    WingAxis1_blinn3_0: THREE.Mesh
    Wing_Right_BODY_SHD_0: THREE.Mesh
    Wing_LefttFlap_blinn2_0: THREE.Mesh
    WingAxis1_blinn3_0_1: THREE.Mesh
    Wing_Left_BODY_SHD_0: THREE.Mesh
    EngineFXBase_lambert2_0: THREE.Mesh
    Lamp_bulb_GLASS_SHD_0: THREE.Mesh
    Lamp_glass_GLASS_SHD_0: THREE.Mesh
    Lamp_case_blinn4_0: THREE.Mesh
    Gyro_lights01_phong8_0: THREE.Mesh
    Gyro_lights02_phong8_0: THREE.Mesh
    GyroAxe_METAL01_SHD_0: THREE.Mesh
    GyroSupport_METAL01_SHD_0: THREE.Mesh
    GyroMirror_METAL01_SHD_0: THREE.Mesh
    GyroBase02_METAL01_SHD_0: THREE.Mesh
    Gyro_Glass_blinn9_0: THREE.Mesh
    GyroBase01_BODY_SHD_0: THREE.Mesh
    GyroBulb_LightBulbShd_0: THREE.Mesh
    TopFlap01_BODY_SHD_0: THREE.Mesh
    TopFlap02_BODY_SHD_0: THREE.Mesh
    AntennaBase_blinn4_0: THREE.Mesh
    Back_screw01_BODY_SHD_0: THREE.Mesh
    Back_screw02_BODY_SHD_0: THREE.Mesh
    Back_screw03_BODY_SHD_0: THREE.Mesh
    Back_screw04_BODY_SHD_0: THREE.Mesh
    Radio_BODY_SHD_0: THREE.Mesh
    WingAxis_supportRight_blinn3_0: THREE.Mesh
    WingAxis_supportLeft_blinn3_0: THREE.Mesh
    Engine_01_METAL01_SHD_0: THREE.Mesh
    Engine_02_METAL01_SHD_0: THREE.Mesh
    Eye_piece04_BODY_SHD_0: THREE.Mesh
    Eye_lens_pupil_blinn6_0: THREE.Mesh
    Eye_Lens_Glass_GLASS_SHD_0: THREE.Mesh
    Eye_lens_Eye_Shd_0: THREE.Mesh
    Eye_lens1_blinn4_0: THREE.Mesh
    EyelidTop_blinn4_0: THREE.Mesh
    EyelidDown_blinn4_0: THREE.Mesh
    Eye_GRP_Glass02_GLASS_SHD_0: THREE.Mesh
    Eye_piece01_blinn4_0: THREE.Mesh
    Texture_plane_lambert3_0: THREE.Mesh
    BODY_BODY_SHD_0: THREE.Mesh
    Object_202: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    _rootJoint_1: THREE.Bone
    _rootJoint_2: THREE.Bone
  }
  materials: {
    blinn3: THREE.MeshStandardMaterial
    FIREFLAMESHD: THREE.MeshStandardMaterial
    blinn2: THREE.MeshStandardMaterial
    blinn3: THREE.MeshStandardMaterial
    BODY_SHD: THREE.MeshStandardMaterial
    lambert2: THREE.MeshStandardMaterial
    GLASS_SHD: THREE.MeshStandardMaterial
    blinn4: THREE.MeshStandardMaterial
    phong8: THREE.MeshStandardMaterial
    METAL01_SHD: THREE.MeshStandardMaterial
    blinn9: THREE.MeshStandardMaterial
    LightBulbShd: THREE.MeshStandardMaterial
    blinn6: THREE.MeshStandardMaterial
    Eye_Shd: THREE.MeshPhysicalMaterial
    lambert3: THREE.MeshStandardMaterial
    blinn5: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/health-bot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={19.049}>
          <group name="c965cff317c44d7bb17826248999bde4fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="HEALTHBOTRIG_GRP">
                  <group name="GlobalScale_GRP">
                    <group name="RIG">
                      <group name="ClusterGRP" position={[0, 0.234, 0]}>
                        <group name="Object_8">
                          <primitive object={nodes._rootJoint} />
                          <group name="Object_26" />
                          <group name="Object_28" rotation={[0, Math.PI / 2, 0]} />
                          <group name="Object_30" rotation={[-Math.PI, 0, -Math.PI]} />
                          <group name="Object_32" rotation={[0, -Math.PI / 2, 0]} />
                          <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.blinn3} skeleton={nodes.Object_27.skeleton} morphTargetDictionary={nodes.Object_27.morphTargetDictionary} morphTargetInfluences={nodes.Object_27.morphTargetInfluences} />
                          <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.blinn3} skeleton={nodes.Object_29.skeleton} morphTargetDictionary={nodes.Object_29.morphTargetDictionary} morphTargetInfluences={nodes.Object_29.morphTargetInfluences} />
                          <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.blinn3} skeleton={nodes.Object_31.skeleton} morphTargetDictionary={nodes.Object_31.morphTargetDictionary} morphTargetInfluences={nodes.Object_31.morphTargetInfluences} />
                          <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.blinn3} skeleton={nodes.Object_33.skeleton} morphTargetDictionary={nodes.Object_33.morphTargetDictionary} morphTargetInfluences={nodes.Object_33.morphTargetInfluences} />
                        </group>
                      </group>
                    </group>
                    <group name="MODGRP">
                      <group name="MOD">
                        <group name="BODYGRP" position={[0, 0.234, 0]}>
                          <group name="Engine_fire_grp" position={[-0.606, -0.96, 0.054]} rotation={[-1.183, -1.255, -1.15]} scale={0.514}>
                            <group name="place3dTexture1" position={[0.013, -7.272, -1.819]} rotation={[1.862, -0.014, -1.444]} scale={1.946} />
                            <group name="Engine_Fire" position={[0.022, 1.909, -0.542]} rotation={[0.255, 0, 0]} scale={[1.584, 0.667, 1.52]} />
                            <group name="Clusters">
                              <group name="group2" position={[0.012, 2.851, -0.335]} rotation={[0.267, -0.004, -0.014]} scale={1.817} />
                              <group name="group3" position={[0.012, 2.851, -0.335]} rotation={[0.267, -0.004, -0.014]} scale={1.817} />
                              <group name="group4" position={[0.012, 2.851, -0.335]} rotation={[0.267, -0.004, -0.014]} scale={1.817} />
                              <group name="group5" position={[0.012, 2.851, -0.335]} rotation={[0.267, -0.004, -0.014]} scale={1.817}>
                                <group name="Object_44">
                                  <primitive object={nodes._rootJoint_1} />
                                  <group name="Object_46" position={[0.012, -0.53, 0.027]} rotation={[-0.012, 0.004, 0.014]} scale={[0.872, 0.367, 0.837]} />
                                  <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.FIREFLAMESHD} skeleton={nodes.Object_47.skeleton} />
                                </group>
                              </group>
                            </group>
                            <group name="Eng_lattice">
                              <group name="ffd4Lattice" position={[-0.012, 0.1, -1.204]} rotation={[0.289, -0.009, 0.036]} scale={[3.756, 8.831, 5.735]} />
                              <group name="ffd4Base" position={[-0.012, 0.1, -1.204]} rotation={[0.289, -0.009, 0.036]} scale={[3.756, 8.831, 5.735]} />
                              <group name="group6" position={[0.071, 2.128, -0.596]} rotation={[0.398, 1.443, -0.107]} scale={1.946}>
                                <group name="cluster10Handle" position={[0.001, -2.789, 0.057]} />
                              </group>
                            </group>
                          </group>
                          <group name="WingsRightGRP" position={[0, 5.362, 3.047]} rotation={[1.408, 0, 0]}>
                            <group name="Wing_RightFlap" position={[1.034, -1.418, 4.329]} rotation={[-1.449, 0, 0]}>
                              <mesh name="Wing_RightFlap_blinn2_0" geometry={nodes.Wing_RightFlap_blinn2_0.geometry} material={materials.blinn2} />
                            </group>
                            <group name="WingAxis1" position={[0.087, -0.288, -0.154]}>
                              <mesh name="WingAxis1_blinn3_0" geometry={nodes.WingAxis1_blinn3_0.geometry} material={materials.blinn3} />
                            </group>
                            <group name="Wing_Right" position={[0.016, 0, -0.017]}>
                              <mesh name="Wing_Right_BODY_SHD_0" geometry={nodes.Wing_Right_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                            </group>
                          </group>
                          <group name="WingsLeftGRP" position={[0, 5.362, -3.04]} rotation={[-1.408, 0, 0]}>
                            <group name="Wing_LefttFlap" position={[-1.034, -1.418, -4.329]}>
                              <mesh name="Wing_LefttFlap_blinn2_0" geometry={nodes.Wing_LefttFlap_blinn2_0.geometry} material={materials.blinn2} />
                            </group>
                            <group name="WingAxis1_1" position={[-0.087, -0.288, 0.154]}>
                              <mesh name="WingAxis1_blinn3_0_1" geometry={nodes.WingAxis1_blinn3_0_1.geometry} material={materials.blinn3} />
                            </group>
                            <group name="Wing_Left" position={[-0.016, 0, 0.017]}>
                              <mesh name="Wing_Left_BODY_SHD_0" geometry={nodes.Wing_Left_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                            </group>
                          </group>
                          <group name="ENGINE_FX_grp">
                            <group name="TrailGRP" position={[0, -0.406, 0]} />
                            <group name="EngineFXBase" position={[0, 1.264, 0]}>
                              <mesh name="EngineFXBase_lambert2_0" geometry={nodes.EngineFXBase_lambert2_0.geometry} material={materials.lambert2} />
                            </group>
                          </group>
                          <group name="LAMP_grp" position={[2.249, 2.058, 0.877]}>
                            <group name="Lamp_bulb" position={[-0.1, 0, 0]}>
                              <mesh name="Lamp_bulb_GLASS_SHD_0" geometry={nodes.Lamp_bulb_GLASS_SHD_0.geometry} material={materials.GLASS_SHD} />
                            </group>
                            <group name="Lamp_glass" position={[0.007, 0, 0]}>
                              <mesh name="Lamp_glass_GLASS_SHD_0" geometry={nodes.Lamp_glass_GLASS_SHD_0.geometry} material={materials.GLASS_SHD} />
                            </group>
                            <group name="Lamp_case">
                              <mesh name="Lamp_case_blinn4_0" geometry={nodes.Lamp_case_blinn4_0.geometry} material={materials.blinn4} />
                            </group>
                          </group>
                          <group name="GYRO_ALL" position={[0, -3.176, 0]}>
                            <group name="Gyromirror_grp" position={[0, 6.412, 0.017]}>
                              <group name="Gyro_lights01" position={[0, 2.196, 0]}>
                                <mesh name="Gyro_lights01_phong8_0" geometry={nodes.Gyro_lights01_phong8_0.geometry} material={materials.phong8} />
                              </group>
                              <group name="Gyro_lights02" position={[0, 2.196, 0]} rotation={[0, 0, -Math.PI]} scale={-1}>
                                <mesh name="Gyro_lights02_phong8_0" geometry={nodes.Gyro_lights02_phong8_0.geometry} material={materials.phong8} />
                              </group>
                              <group name="GyroAxe" position={[0, 1.285, -0.017]}>
                                <mesh name="GyroAxe_METAL01_SHD_0" geometry={nodes.GyroAxe_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                              </group>
                              <group name="GyroSupport" position={[0.027, 1.288, -0.017]}>
                                <mesh name="GyroSupport_METAL01_SHD_0" geometry={nodes.GyroSupport_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                              </group>
                              <group name="GyroMirror" position={[-0.446, 2.06, -0.017]}>
                                <mesh name="GyroMirror_METAL01_SHD_0" geometry={nodes.GyroMirror_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                              </group>
                            </group>
                            <group name="Gyro_grp">
                              <group name="GyroBase02">
                                <mesh name="GyroBase02_METAL01_SHD_0" geometry={nodes.GyroBase02_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                              </group>
                              <group name="Gyro_Glass">
                                <mesh name="Gyro_Glass_blinn9_0" geometry={nodes.Gyro_Glass_blinn9_0.geometry} material={materials.blinn9} />
                              </group>
                              <group name="GyroBase01">
                                <mesh name="GyroBase01_BODY_SHD_0" geometry={nodes.GyroBase01_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                              </group>
                              <group name="GyroBulb">
                                <mesh name="GyroBulb_LightBulbShd_0" geometry={nodes.GyroBulb_LightBulbShd_0.geometry} material={materials.LightBulbShd} />
                              </group>
                            </group>
                          </group>
                          <group name="TopFlap01_offset" position={[0.025, 6.822, 0.984]}>
                            <group name="TopFlap01" position={[-0.025, 0, -0.973]} scale={[0.989, 0.747, 1]}>
                              <mesh name="TopFlap01_BODY_SHD_0" geometry={nodes.TopFlap01_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                            </group>
                          </group>
                          <group name="TopFlap02_offset" position={[0.025, 6.822, -0.989]}>
                            <group name="TopFlap02" position={[-0.025, 0, 0.973]} rotation={[0, 0, -Math.PI]} scale={[-0.989, -0.747, -1]}>
                              <mesh name="TopFlap02_BODY_SHD_0" geometry={nodes.TopFlap02_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                            </group>
                          </group>
                          <group name="AntennaBase_1" position={[-3.392, 5.303, -1.292]} scale={[0.14, 1, 0.14]}>
                            <mesh name="AntennaBase_blinn4_0" geometry={nodes.AntennaBase_blinn4_0.geometry} material={materials.blinn4} />
                          </group>
                          <group name="Antenna" />
                          <group name="BODY_OLD" />
                          <group name="Radiogrp" position={[0, 3.819, 0]} scale={6.933}>
                            <group name="Radio_old" />
                            <group name="Radio" position={[0, -0.551, 0]} scale={0.144}>
                              <group name="Back_screw01">
                                <mesh name="Back_screw01_BODY_SHD_0" geometry={nodes.Back_screw01_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                              </group>
                              <group name="Back_screw02">
                                <mesh name="Back_screw02_BODY_SHD_0" geometry={nodes.Back_screw02_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                              </group>
                              <group name="Back_screw03">
                                <mesh name="Back_screw03_BODY_SHD_0" geometry={nodes.Back_screw03_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                              </group>
                              <group name="Back_screw04">
                                <mesh name="Back_screw04_BODY_SHD_0" geometry={nodes.Back_screw04_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                              </group>
                              <mesh name="Radio_BODY_SHD_0" geometry={nodes.Radio_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                            </group>
                          </group>
                          <group name="WingAxis_supportRight">
                            <mesh name="WingAxis_supportRight_blinn3_0" geometry={nodes.WingAxis_supportRight_blinn3_0.geometry} material={materials.blinn3} />
                          </group>
                          <group name="WingAxis_supportLeft">
                            <mesh name="WingAxis_supportLeft_blinn3_0" geometry={nodes.WingAxis_supportLeft_blinn3_0.geometry} material={materials.blinn3} />
                          </group>
                          <group name="PADSGRP">
                            <group name="Pad01" />
                            <group name="Pad02" rotation={[0, Math.PI / 2, 0]} />
                            <group name="Pad03" rotation={[-Math.PI, 0, -Math.PI]} />
                            <group name="Pad04" rotation={[0, -Math.PI / 2, 0]} />
                          </group>
                          <group name="Engine_01">
                            <mesh name="Engine_01_METAL01_SHD_0" geometry={nodes.Engine_01_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                          </group>
                          <group name="Engine_02">
                            <mesh name="Engine_02_METAL01_SHD_0" geometry={nodes.Engine_02_METAL01_SHD_0.geometry} material={materials.METAL01_SHD} />
                          </group>
                          <group name="Eye_piece04" position={[-0.551, -0.368, 0]} scale={[1, 1.079, 1.079]}>
                            <mesh name="Eye_piece04_BODY_SHD_0" geometry={nodes.Eye_piece04_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                          </group>
                          <group name="EYEGRP">
                            <group name="Eye_LensGRP" position={[-1.617, -2.793, 0]} scale={[1, 1.6, 1.6]}>
                              <group name="Eye_lens_pupil" position={[4.216, 4.655, 0]} scale={[1, 0.738, 0.738]}>
                                <mesh name="Eye_lens_pupil_blinn6_0" geometry={nodes.Eye_lens_pupil_blinn6_0.geometry} material={materials.blinn6} />
                              </group>
                              <group name="Eye_Lens_Glass">
                                <mesh name="Eye_Lens_Glass_GLASS_SHD_0" geometry={nodes.Eye_Lens_Glass_GLASS_SHD_0.geometry} material={materials.GLASS_SHD} />
                              </group>
                              <group name="Eye_lens" position={[-0.019, 0, 0]}>
                                <mesh name="Eye_lens_Eye_Shd_0" geometry={nodes.Eye_lens_Eye_Shd_0.geometry} material={materials.Eye_Shd} />
                              </group>
                              <group name="Eye_lens1" position={[0.055, 0.063, 0]} scale={0.987}>
                                <mesh name="Eye_lens1_blinn4_0" geometry={nodes.Eye_lens1_blinn4_0.geometry} material={materials.blinn4} />
                              </group>
                            </group>
                            <group name="EYELIDGRP">
                              <group name="EyelidTop" position={[2.699, 4.655, 0]}>
                                <mesh name="EyelidTop_blinn4_0" geometry={nodes.EyelidTop_blinn4_0.geometry} material={materials.blinn4} />
                              </group>
                              <group name="EyelidDown" position={[2.699, 4.655, 0]}>
                                <mesh name="EyelidDown_blinn4_0" geometry={nodes.EyelidDown_blinn4_0.geometry} material={materials.blinn4} />
                              </group>
                            </group>
                            <group name="Eye_GRP_Glass02">
                              <mesh name="Eye_GRP_Glass02_GLASS_SHD_0" geometry={nodes.Eye_GRP_Glass02_GLASS_SHD_0.geometry} material={materials.GLASS_SHD} />
                            </group>
                            <group name="Eye_piece01">
                              <mesh name="Eye_piece01_blinn4_0" geometry={nodes.Eye_piece01_blinn4_0.geometry} material={materials.blinn4} />
                            </group>
                          </group>
                          <group name="topflap_ffd2Base" position={[0.025, 3.477, 0.011]} scale={[6.211, 6.954, 6.711]} />
                          <group name="topflap_ffd2Lattice" position={[0.025, 3.477, 0.011]} scale={[6.211, 6.954, 6.711]} />
                          <group name="BODY_1">
                            <group name="Texture_plane" position={[2.453, 2.095, -0.775]} rotation={[0, 0, 1.392]} scale={0.001}>
                              <mesh name="Texture_plane_lambert3_0" geometry={nodes.Texture_plane_lambert3_0.geometry} material={materials.lambert3} />
                            </group>
                            <mesh name="BODY_BODY_SHD_0" geometry={nodes.BODY_BODY_SHD_0.geometry} material={materials.BODY_SHD} />
                          </group>
                          <group name="Down_strap" />
                          <group name="Eyelid_ffd3Lattice" position={[1.748, 4.652, 0]} scale={[1.4, 2.486, 2.652]} />
                          <group name="Eyelid_ffd3Base" position={[1.748, 4.652, 0]} scale={[1.4, 2.486, 2.652]} />
                        </group>
                      </group>
                    </group>
                    <group name="CTRLs">
                      <group name="MAIN" position={[0, -0.486, 0]}>
                        <group name="ROOT" position={[0, 0.234, 0]}>
                          <group name="FLY" position={[-0.001, 3.596, 0]}>
                            <group name="BODYgrp_offset" position={[0.001, -3.11, 0]}>
                              <group name="BODY" position={[0, 2.877, 0]}>
                                <group name="AntennaBase" position={[-3.383, 3.426, -1.292]}>
                                  <group name="Ant01" position={[0, 1.585, 0]} rotation={[-0.078, 0, 0]}>
                                    <group name="Ant02" position={[0, 1.302, 0]}>
                                      <group name="Ant03" position={[0, 1.387, 0]}>
                                        <group name="Ant04" position={[0, 1.553, 0]}>
                                          <group name="Ant05" position={[0, 1.677, 0]}>
                                            <group name="Ant06" position={[0, 1.158, 0]} />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                                <group name="GyroCtrl_offset" position={[0, 1.556, 0]}>
                                  <group name="GyroCtrl" />
                                </group>
                                <group name="Fire_Engine" position={[0.024, -3.709, -0.016]} rotation={[-1.183, -1.255, -1.15]} scale={0.514}>
                                  <group name="Engine_ctrl_offset" position={[0, -2.325, -0.402]} rotation={[0.274, 0, 0]} scale={2.223}>
                                    <group name="Engine_ctrl" />
                                  </group>
                                </group>
                                <group name="CTRL_FLAPSRightGRP" position={[0, 2.431, -0.007]}>
                                  <group name="Ctrl_FlapRight01" position={[-0.008, 0, 3.018]} rotation={[1.408, 0, 0]}>
                                    <group name="Ctrl_FlapRight02GRP" position={[0, -1.364, 4.365]}>
                                      <group name="Ctrl_FlapRight02" />
                                    </group>
                                  </group>
                                </group>
                                <group name="EyesCtrlGrp" position={[6.336, 1.777, 0]}>
                                  <group name="Ctrl_EyeALL">
                                    <group name="Ctrl_pupil" />
                                  </group>
                                </group>
                                <group name="FX_Ctrl" position={[0, -3.916, 0]} />
                                <group name="Trail_shape_ctrl" position={[0, -4.314, 0]} />
                                <group name="TrailSHAPEDEF_GRP" position={[0, -2.877, 0]}>
                                  <group name="FX_deformer" />
                                </group>
                                <group name="CTRL_FLAPSLeftGRP" position={[0, 2.431, -0.007]} rotation={[0, 0, -Math.PI]} scale={-1}>
                                  <group name="Ctrl_FlapRight01_1" position={[-0.008, 0, 3.018]} rotation={[1.408, 0, 0]}>
                                    <group name="Ctrl_FlapRight02GRP_1" position={[0, -1.364, 4.365]}>
                                      <group name="Ctrl_FlapRight02_1" />
                                    </group>
                                  </group>
                                </group>
                                <group name="AntennaChainGRP" position={[0, -2.877, 0]}>
                                  <group name="Antenna_Chain">
                                    <group name="Object_199">
                                      <primitive object={nodes._rootJoint_2} />
                                      <group name="Object_201" />
                                      <skinnedMesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.blinn5} skeleton={nodes.Object_202.skeleton} />
                                    </group>
                                  </group>
                                </group>
                                <group name="ffd1Lattice" position={[0.002, -3.382, -0.004]} scale={[1.852, 1.077, 1.852]} />
                                <group name="ffd1Base" position={[0.002, -3.382, -0.004]} scale={[1.852, 1.077, 1.852]} />
                                <group name="Clustergrp" position={[0.251, -3.399, 0.246]}>
                                  <group name="cluster1Handle" position={[-0.249, -0.521, -0.25]} />
                                </group>
                                <group name="Right_TopFlap_offset" position={[0, -2.877, 0]}>
                                  <group name="Right_TopFlap_ctrl" position={[0, 7.552, 1.585]} />
                                </group>
                                <group name="Left_TopFlap_offset" position={[0, -2.877, 0]} rotation={[0, 0, -Math.PI]} scale={-1}>
                                  <group name="Left_TopFlap_ctrl" position={[0, 7.552, 1.612]} />
                                </group>
                                <group name="PADS01_grp" position={[0, -2.877, 0]}>
                                  <group name="Pad01_deform01_offset" position={[2.139, 0.065, 2.118]} rotation={[1.76, -0.219, -0.85]}>
                                    <group name="Pad01_deform01" />
                                  </group>
                                  <group name="Pad01_deform02_offset" position={[2.044, -0.391, 1.123]} rotation={[1.591, -0.513, -2.572]}>
                                    <group name="Pad01_deform02" />
                                  </group>
                                  <group name="Pad01_deform03_offset" position={[1.159, -0.417, 2.058]} rotation={[2.207, 0.004, 0.845]}>
                                    <group name="Pad01_deform03" />
                                  </group>
                                  <group name="Pad01_deform04_offset" position={[1.453, -0.73, 1.426]} rotation={[3.14, 0.737, 0.459]}>
                                    <group name="Pad01_deform04" />
                                  </group>
                                </group>
                                <group name="PADS01_grp1" position={[0, -2.877, 0]} rotation={[0, Math.PI / 2, 0]}>
                                  <group name="Pad01_deform01_offset_1" position={[2.139, 0.065, 2.118]} rotation={[1.76, -0.219, -0.85]}>
                                    <group name="Pad01_deform01_1" />
                                  </group>
                                  <group name="Pad01_deform02_offset_1" position={[2.044, -0.391, 1.123]} rotation={[1.591, -0.513, -2.572]}>
                                    <group name="Pad01_deform02_1" />
                                  </group>
                                  <group name="Pad01_deform03_offset_1" position={[1.159, -0.417, 2.058]} rotation={[2.207, 0.004, 0.845]}>
                                    <group name="Pad01_deform03_1" />
                                  </group>
                                  <group name="Pad01_deform04_offset_1" position={[1.453, -0.73, 1.426]} rotation={[3.14, 0.737, 0.459]}>
                                    <group name="Pad01_deform04_1" />
                                  </group>
                                </group>
                                <group name="PADS01_grp2" position={[0, -2.877, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                                  <group name="Pad01_deform01_offset_2" position={[2.139, 0.065, 2.118]} rotation={[1.76, -0.219, -0.85]}>
                                    <group name="Pad01_deform01_2" />
                                  </group>
                                  <group name="Pad01_deform02_offset_2" position={[2.044, -0.391, 1.123]} rotation={[1.591, -0.513, -2.572]}>
                                    <group name="Pad01_deform02_2" />
                                  </group>
                                  <group name="Pad01_deform03_offset_2" position={[1.159, -0.417, 2.058]} rotation={[2.207, 0.004, 0.845]}>
                                    <group name="Pad01_deform03_2" />
                                  </group>
                                  <group name="Pad01_deform04_offset_2" position={[1.453, -0.73, 1.426]} rotation={[3.14, 0.737, 0.459]}>
                                    <group name="Pad01_deform04_2" />
                                  </group>
                                </group>
                                <group name="PADS01_grp3" position={[0, -2.877, 0]} rotation={[0, -Math.PI / 2, 0]}>
                                  <group name="Pad01_deform01_offset_3" position={[2.139, 0.065, 2.118]} rotation={[1.76, -0.219, -0.85]}>
                                    <group name="Pad01_deform01_3" />
                                  </group>
                                  <group name="Pad01_deform02_offset_3" position={[2.044, -0.391, 1.123]} rotation={[1.591, -0.513, -2.572]}>
                                    <group name="Pad01_deform02_3" />
                                  </group>
                                  <group name="Pad01_deform03_offset_3" position={[1.159, -0.417, 2.058]} rotation={[2.207, 0.004, 0.845]}>
                                    <group name="Pad01_deform03_3" />
                                  </group>
                                  <group name="Pad01_deform04_offset_3" position={[1.453, -0.73, 1.426]} rotation={[3.14, 0.737, 0.459]}>
                                    <group name="Pad01_deform04_3" />
                                  </group>
                                </group>
                                <group name="Flashlight_ctrloffset" position={[3.014, -0.767, 0.966]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
                                  <group name="Flashlight_ctrl" />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/health-bot.glb')
